// AUTHORED island data-as-code -- the overworld floor + props. Generated once from the
// Godot set by tools/layout_to_island.py; from here on this file IS the source of truth
// and is edited by hand (ClaudeCraft-style). See src/world/hexGrid.ts for the grid math.
//
// tiles: axial (q, r) on a pointy-top hex grid; t = KayKit hex code (hex_<t>.gltf);
//        rot = yaw in 60-degree steps (0-5). Tiles may stack (a coast over its water).
// props: on a cell (q, r) or at world (x, z); rot = yaw in degrees; s = scale; y = height.
import type { IslandDef } from "../../world/hexGrid";

export const OVERWORLD: IslandDef = {
  tiles: [
    // row r=-5
    { q: 1, r: -5, t: "water" },
    { q: 2, r: -5, t: "water" },
    { q: 3, r: -5, t: "water" },
    { q: 4, r: -5, t: "water" },
    { q: 5, r: -5, t: "water" },
    { q: 6, r: -5, t: "water" },
    { q: 7, r: -5, t: "water" },
    { q: 8, r: -5, t: "water" },
    { q: 9, r: -5, t: "water" },
    { q: 10, r: -5, t: "water" },
    // row r=-4
    { q: 1, r: -4, t: "water" },
    { q: 2, r: -4, t: "water" },
    { q: 3, r: -4, t: "water" },
    { q: 4, r: -4, t: "water" },
    { q: 5, r: -4, t: "water" },
    { q: 6, r: -4, t: "water" },
    { q: 7, r: -4, t: "water" },
    { q: 8, r: -4, t: "water" },
    { q: 9, r: -4, t: "water" },
    { q: 10, r: -4, t: "water" },
    // row r=-3
    { q: 0, r: -3, t: "water" },
    { q: 1, r: -3, t: "water" },
    { q: 2, r: -3, t: "water" },
    { q: 3, r: -3, t: "water" },
    { q: 4, r: -3, t: "water" },
    { q: 5, r: -3, t: "water" },
    { q: 6, r: -3, t: "water" },
    { q: 7, r: -3, t: "water" },
    { q: 8, r: -3, t: "water" },
    { q: 9, r: -3, t: "water" },
    // row r=-2
    { q: -1, r: -2, t: "water" },
    { q: 0, r: -2, t: "grass" },
    { q: 1, r: -2, t: "grass" },
    { q: 2, r: -2, t: "road_M", rot: 1 },
    { q: 3, r: -2, t: "water" },
    { q: 4, r: -2, t: "water" },
    { q: 5, r: -2, t: "water" },
    { q: 6, r: -2, t: "water" },
    { q: 7, r: -2, t: "water" },
    { q: 8, r: -2, t: "water" },
    { q: 9, r: -2, t: "water" },
    // row r=-1
    { q: -2, r: -1, t: "grass" },
    { q: -1, r: -1, t: "grass" },
    { q: 0, r: -1, t: "grass" },
    { q: 1, r: -1, t: "road_A", rot: 1 },
    { q: 2, r: -1, t: "grass" },
    { q: 3, r: -1, t: "water" },
    { q: 4, r: -1, t: "water" },
    { q: 5, r: -1, t: "water" },
    { q: 6, r: -1, t: "water" },
    { q: 7, r: -1, t: "water" },
    { q: 8, r: -1, t: "water" },
    // row r=0
    { q: -3, r: 0, t: "road_B", rot: 2 },
    { q: -2, r: 0, t: "grass" },
    { q: -1, r: 0, t: "road_B", rot: 3 },
    { q: 0, r: 0, t: "road_D" },
    { q: 1, r: 0, t: "grass" },
    { q: 2, r: 0, t: "grass" },
    { q: 3, r: 0, t: "water" },
    { q: 4, r: 0, t: "water" },
    { q: 5, r: 0, t: "water" },
    { q: 6, r: 0, t: "water" },
    { q: 7, r: 0, t: "water" },
    { q: 8, r: 0, t: "water" },
    // row r=1
    { q: -4, r: 1, t: "grass" },
    { q: -3, r: 1, t: "road_B", rot: 5 },
    { q: -2, r: 1, t: "road_B" },
    { q: -1, r: 1, t: "grass" },
    { q: 0, r: 1, t: "road_E", rot: 5 },
    { q: 1, r: 1, t: "road_M" },
    { q: 2, r: 1, t: "water" },
    { q: 3, r: 1, t: "water" },
    { q: 4, r: 1, t: "water" },
    { q: 5, r: 1, t: "water" },
    { q: 6, r: 1, t: "water" },
    { q: 7, r: 1, t: "water" },
    // row r=2
    { q: -5, r: 2, t: "grass" },
    { q: -4, r: 2, t: "grass" },
    { q: -3, r: 2, t: "grass" },
    { q: -2, r: 2, t: "grass" },
    { q: -1, r: 2, t: "grass" },
    { q: 0, r: 2, t: "road_B", rot: 1 },
    { q: 1, r: 2, t: "water" },
    { q: 2, r: 2, t: "water" },
    { q: 3, r: 2, t: "water" },
    { q: 4, r: 2, t: "water" },
    { q: 5, r: 2, t: "water" },
    { q: 6, r: 2, t: "water" },
    { q: 7, r: 2, t: "water" },
    // row r=3
    { q: -6, r: 3, t: "water" },
    { q: -5, r: 3, t: "water" },
    { q: -4, r: 3, t: "water" },
    { q: -3, r: 3, t: "coast_D", rot: 4 },
    { q: -3, r: 3, t: "water" },
    { q: -2, r: 3, t: "coast_A", rot: 5 },
    { q: -2, r: 3, t: "water" },
    { q: -1, r: 3, t: "road_M", rot: 4 },
    { q: 0, r: 3, t: "grass" },
    { q: 1, r: 3, t: "water" },
    { q: 2, r: 3, t: "water" },
    { q: 3, r: 3, t: "water" },
    { q: 4, r: 3, t: "water" },
    { q: 5, r: 3, t: "water" },
    { q: 6, r: 3, t: "water" },
    // row r=4
    { q: -8, r: 4, t: "water" },
    { q: -7, r: 4, t: "water" },
    { q: -6, r: 4, t: "water" },
    { q: -5, r: 4, t: "water" },
    { q: -4, r: 4, t: "water" },
    { q: -3, r: 4, t: "water" },
    { q: -2, r: 4, t: "coast_C", rot: 5 },
    { q: -2, r: 4, t: "water" },
    { q: -1, r: 4, t: "coast_D" },
    { q: -1, r: 4, t: "water" },
    { q: 0, r: 4, t: "water" },
    { q: 1, r: 4, t: "water" },
    { q: 2, r: 4, t: "water" },
    { q: 3, r: 4, t: "water" },
    { q: 4, r: 4, t: "water" },
    { q: 5, r: 4, t: "water" },
    { q: 6, r: 4, t: "water" },
    // row r=5
    { q: -8, r: 5, t: "water" },
    { q: -7, r: 5, t: "water" },
    { q: -6, r: 5, t: "water" },
    { q: -5, r: 5, t: "water" },
    { q: -4, r: 5, t: "water" },
    { q: -3, r: 5, t: "water" },
    { q: -2, r: 5, t: "water" },
    { q: -1, r: 5, t: "water" },
    { q: 0, r: 5, t: "water" },
    { q: 1, r: 5, t: "water" },
    { q: 2, r: 5, t: "water" },
    { q: 3, r: 5, t: "water" },
    { q: 4, r: 5, t: "water" },
    { q: 5, r: 5, t: "water" },
    // row r=6
    { q: -10, r: 6, t: "water" },
    { q: -9, r: 6, t: "water" },
    { q: -8, r: 6, t: "water" },
    { q: -7, r: 6, t: "water" },
    { q: -6, r: 6, t: "water" },
    { q: -5, r: 6, t: "water" },
    { q: -4, r: 6, t: "water" },
    { q: -3, r: 6, t: "water" },
    { q: -2, r: 6, t: "water" },
    { q: -1, r: 6, t: "water" },
    { q: 0, r: 6, t: "water" },
    { q: 1, r: 6, t: "water" },
    { q: 2, r: 6, t: "water" },
    { q: 3, r: 6, t: "water" },
    { q: 4, r: 6, t: "water" },
    { q: 5, r: 6, t: "water" },
    // row r=7
    { q: -10, r: 7, t: "water" },
    { q: -9, r: 7, t: "water" },
    { q: -8, r: 7, t: "water" },
    { q: -7, r: 7, t: "water" },
    { q: -6, r: 7, t: "water" },
    { q: -5, r: 7, t: "water" },
    { q: -4, r: 7, t: "water" },
    { q: -3, r: 7, t: "water" },
    { q: -2, r: 7, t: "water" },
    { q: -1, r: 7, t: "water" },
    { q: 0, r: 7, t: "water" },
    { q: 1, r: 7, t: "water" },
    { q: 2, r: 7, t: "water" },
    { q: 3, r: 7, t: "water" },
    { q: 4, r: 7, t: "water" },
  ],
  props: [
    { m: "kaykit/hexagon/building_blacksmith_red.gltf", q: 2, r: -2, rot: 330, s: 3 },
    { m: "kaykit/hexagon/building_archeryrange_red.gltf", q: 1, r: 1, rot: 240, s: 3 },
    { m: "kaykit/hexagon/trees_A_large.gltf", q: -2, r: 1, rot: 120, s: 3, y: 0.152 },
    { m: "kaykit/hexagon/trees_A_medium.gltf", q: -1, r: -1, rot: 60, s: 3 },
    { m: "kaykit/hexagon/trees_B_medium.gltf", q: -2, r: 2, rot: 150, s: 3 },
    { m: "kaykit/hexagon/mountain_A_grass_trees.gltf", q: 0, r: -2, rot: 30, s: 3 },
    { m: "kaykit/hexagon/building_windmill_red.gltf", x: 2.701, z: 15.569, rot: 127.243, s: 3 },
    { m: "kaykit/hexagon/tree_single_A.gltf", q: 2, r: 0, s: 3 },
    { m: "kaykit/hexagon/flag_red.gltf", x: -8.556, z: 1.514, s: 3 },
    { m: "kaykit/hexagon/flag_red.gltf", x: 3.6, z: -8.792, s: 3 },
    { m: "kaykit/hexagon/flag_red.gltf", x: 6.6, z: 3.996, s: 3 },
    { m: "kaykit/hexagon/cloud_big.gltf", x: -9, z: -10.392, s: 3, y: 10 },
    { m: "kaykit/hexagon/cloud_big.gltf", x: 10.8, z: 6.235, s: 3, y: 13 },
    { m: "kaykit/forest_nature/Rock_1_A_Color1.gltf", x: -0.073, z: 2.235, s: 1 },
    { m: "kaykit/forest_nature/Bush_4_A_Color1.gltf", x: 3.096, z: 3.056, s: 1 },
    { m: "kaykit/forest_nature/Bush_3_B_Color1.gltf", x: -4.547, z: 1.982, s: 1 },
    { m: "kaykit/forest_nature/Bush_2_C_Color1.gltf", x: -4.557, z: 3.255, s: 1 },
    { m: "kaykit/hexagon/building_home_A_red.gltf", x: -2.203, z: 3.767, rot: 149.85, s: 3.2, y: 0.021 },
    { m: "kaykit/hexagon/hills_C_trees.gltf", q: -2, r: 0, s: 3 },
  ],
};
