#!/usr/bin/env python3
"""Generate src/audio/tracks.generated.ts -- the music manifest.

The Godot player lists its folders at runtime; a browser cannot, so the playlists are baked
here. Re-run when tracks are added to assets/audio/music/<context>/.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MUSIC = os.path.join(HERE, "..", "public", "audio", "music")
OUT = os.path.join(HERE, "..", "src", "audio", "tracks.generated.ts")
EXTS = (".ogg", ".mp3", ".wav")

lines = [
    "// GENERATED by tools/gen_music.py -- do not edit. One playlist per context, mirroring",
    "// assets/audio/music/<context>/. Paths are served, not bundled: tracks stream on demand.",
    "",
    "export const TRACKS: Record<string, string[]> = {",
]
total = 0
for ctx in sorted(os.listdir(MUSIC)):
    d = os.path.join(MUSIC, ctx)
    if not os.path.isdir(d):
        continue
    files = sorted(f for f in os.listdir(d) if f.lower().endswith(EXTS))
    total += len(files)
    lines.append(f'  {ctx}: [')
    for f in files:
        lines.append(f'    "/audio/music/{ctx}/{f}",')
    lines.append("  ],")
lines += ["};", ""]
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(lines))
print(f"{total} tracks across {len(os.listdir(MUSIC))} contexts -> {os.path.relpath(OUT, HERE)}")
