#!/usr/bin/env python3
"""Generate src/editor/catalog.generated.ts: the editor palette.

Walks the KayKit packs served under public/assets (a symlink to the committed asset tree).
  TILES -- hexagon/hex_*.gltf, keyed by the code after `hex_` (what IslandDef.tiles[].t holds)
  PROPS -- every other .gltf in the hexagon + forest_nature packs (buildings, trees, rocks...)
Re-run when a pack is added. Labels are humanised file names.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "public", "assets")
PACKS = ["kaykit/hexagon", "kaykit/forest_nature"]
OUT = os.path.join(HERE, "..", "src", "editor", "catalog.generated.ts")


def label(name):
    return re.sub(r"_+", " ", name).strip().capitalize()


def category(pack, name):
    if pack.endswith("forest_nature"):
        return "nature"
    for k in ("building", "wall", "fence", "tree", "trees", "hill", "hills", "mountain", "rock", "cloud", "flag", "crate", "resource", "water"):
        if name.startswith(k):
            return {"trees": "tree", "hills": "hill", "waterlily": "water", "waterplant": "water"}.get(k, k)
    return "misc"


tiles, props = [], []
for pack in PACKS:
    d = os.path.join(ROOT, pack)
    for f in sorted(os.listdir(d)):
        if not f.endswith(".gltf"):
            continue
        name = f[:-5]
        if name.startswith("hex_"):
            tiles.append((name[4:], label(name[4:])))
        else:
            props.append((f"{pack}/{f}", category(pack, name), label(name)))

lines = ["// GENERATED by tools/gen_catalog.py -- do not edit. The editor palette.", "",
         "export interface TileEntry { code: string; label: string }",
         "export interface PropEntry { path: string; category: string; label: string }", "",
         "export const TILES: TileEntry[] = ["]
lines += [f'  {{ code: "{c}", label: "{l}" }},' for c, l in tiles]
lines += ["];", "", "export const PROPS: PropEntry[] = ["]
lines += [f'  {{ path: "{p}", category: "{cat}", label: "{l}" }},' for p, cat, l in props]
lines += ["];", "",
          "export const PROP_CATEGORIES: string[] = [...new Set(PROPS.map((p) => p.category))].sort();", ""]
open(OUT, "w").write("\n".join(lines))
print(f"catalog: {len(tiles)} tiles, {len(props)} props -> {os.path.relpath(OUT, HERE)}")
