// GENERATED by tools/gen_music.py -- do not edit. One playlist per context, mirroring
// assets/audio/music/<context>/. Paths are served, not bundled: tracks stream on demand.

export const TRACKS: Record<string, string[]> = {
  adventure: [
    "/audio/music/adventure/02 - Enchanted Roads.ogg",
    "/audio/music/adventure/05 - Westward Winds.ogg",
    "/audio/music/adventure/06 - The Farther Shore.ogg",
    "/audio/music/adventure/09 - Stones Remember.ogg",
    "/audio/music/adventure/10 - Hearthsong.ogg",
  ],
  menu: [
    "/audio/music/menu/01 - Quiet Menu.ogg",
    "/audio/music/menu/02 - Resting Place.ogg",
    "/audio/music/menu/03 - Safe Haven.ogg",
    "/audio/music/menu/04 - World Map.ogg",
    "/audio/music/menu/05 - Between Journeys.ogg",
  ],
  overworld: [
    "/audio/music/overworld/01 - The Far Quiet.ogg",
    "/audio/music/overworld/02 - Fallow Lands.ogg",
    "/audio/music/overworld/03 - Lantern Ashes.ogg",
    "/audio/music/overworld/04 - Quiet Crossing.ogg",
    "/audio/music/overworld/05 - Under Pale Skies.ogg",
  ],
};
